"use server";
import { revalidatePath } from "next/cache";
import { requireUser } from "@/lib/auth";
export type ActionState = { error?: string; message?: string };
const number = (value: FormDataEntryValue | null) => Number(value ?? 0);
const invalidate = () => ["/dashboard", "/products", "/stock", "/stock/in", "/stock/out", "/sales", "/reports"].forEach((path) => revalidatePath(path));
export async function saveProduct(_: ActionState, form: FormData): Promise<ActionState> { const { supabase, user } = await requireUser(); const name = String(form.get("name") ?? "").trim(); const sku = String(form.get("sku") ?? "").trim() || null; const category = String(form.get("category") ?? "").trim() || null; const cost = number(form.get("costPrice")); const selling = number(form.get("sellingPrice")); const threshold = number(form.get("threshold")); if (!name) return { error: "Product name is required." }; if ([cost, selling, threshold].some((v) => !Number.isFinite(v) || v < 0) || !Number.isInteger(threshold)) return { error: "Enter valid, non-negative prices and stock threshold." }; const payload = { user_id: user.id, name, sku, category, cost_price: cost, selling_price: selling, low_stock_threshold: threshold }; const { error } = await supabase.from("products").insert(payload); if (error) return { error: error.code === "23505" ? "That SKU is already in use." : "Unable to save product. Please try again." }; invalidate(); return { message: "Product created successfully." }; }
export async function updateProduct(_: ActionState, form: FormData): Promise<ActionState> { const { supabase } = await requireUser(); const id = String(form.get("id") ?? ""); const name = String(form.get("name") ?? "").trim(); const sku = String(form.get("sku") ?? "").trim() || null; const category = String(form.get("category") ?? "").trim() || null; const cost = number(form.get("costPrice")); const selling = number(form.get("sellingPrice")); const threshold = number(form.get("threshold")); if (!id || !name || [cost, selling, threshold].some((v) => !Number.isFinite(v) || v < 0) || !Number.isInteger(threshold)) return { error: "Please provide valid product details." }; const { error } = await supabase.from("products").update({ name, sku, category, cost_price: cost, selling_price: selling, low_stock_threshold: threshold }).eq("id", id); if (error) return { error: "Unable to update this product." }; invalidate(); return { message: "Product updated successfully." }; }
export async function deleteProduct(id: string): Promise<ActionState> { const { supabase } = await requireUser(); const { error } = await supabase.from("products").delete().eq("id", id); if (error) return { error: "Unable to delete this product." }; invalidate(); return { message: "Product deleted." }; }
export async function recordMovement(_: ActionState, form: FormData): Promise<ActionState> { const { supabase } = await requireUser(); const productId = String(form.get("productId") ?? ""); const type = String(form.get("type") ?? ""); const quantity = number(form.get("quantity")); const priceRaw = String(form.get("unitPrice") ?? ""); const unitPrice = priceRaw === "" ? null : number(priceRaw); if (!productId || (type !== "IN" && type !== "OUT") || !Number.isInteger(quantity) || quantity <= 0 || (unitPrice !== null && (!Number.isFinite(unitPrice) || unitPrice < 0))) return { error: "Select a product and enter a valid quantity." }; const { error } = await supabase.rpc("record_inventory_movement", { p_product_id: productId, p_movement_type: type, p_quantity: quantity, p_unit_price: unitPrice, p_reference: String(form.get("reference") ?? ""), p_note: String(form.get("note") ?? ""), p_customer: String(form.get("customer") ?? "") }); if (error) return { error: error.message.includes("Insufficient") ? "There is not enough stock available for this transaction." : "Unable to record the movement. Please try again." }; invalidate(); return { message: type === "IN" ? "Stock added successfully." : unitPrice === null ? "Stock removed successfully." : "Sale recorded successfully." }; }
